apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-app-multi-components-repo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-app-multi-components-repo
    app.kubernetes.io/part-of: test-application
  name: python-app-multi-components-repo
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-app-multi-components-repo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-app-multi-components-repo
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jephilli-tenant/test-application/python-app-multi-components-repo@sha256:1bcf6764c29cbfdd65b961376b9b1ca229e6a7ed048c5fe37135499c6979ec6d
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
