apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: human-resources
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jephilli-tenant/test-application/human-resources@sha256:b78164eb2c038ee44288265e77df7c834be79e245fa14ee8b8ba510aa318cce5
        name: my-java-springboot
        resources: {}
status: {}
