apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-ccgs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-ccgs
    app.kubernetes.io/part-of: test-application
  name: pacman-ccgscro0
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: pacman-ccgs
    weight: 100
status: {}
