apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: human-resources
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: human-resources
    app.kubernetes.io/part-of: test-application
  name: human-resources
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: human-resources
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: human-resources
    spec:
      containers:
      - env:
        - name: IMAGE_URL
          value: quay.io/redhat-user-workloads-stage/test-ns/test-application/human-resources:3450decf7174f23304c8e523bc998526ef57e559
        - name: IMAGE_DIGEST
          value: sha256:1d6da200c8ae98384a35bae37516d07b453dde85a91ff891ce57f3a99d420e6a
        image: quay.io/redhat-user-workloads-stage/jephilli-tenant/test-application/human-resources@sha256:70c8bfe0dc7bf2e24dc816eef123da8f83a3b42d06a41954248d0011a7d58645
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
