apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-app-multi-components-repo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jephilli-tenant/test-application/nodejs-app-multi-components-repo@sha256:674cec67cc41f185da51da713615ae164c8c8f08c57c1a03bf791b840127ab85
        name: my-nodejs
        resources: {}
status: {}
