apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-app-multi-components-repo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jephilli-tenant/test-application/python-app-multi-components-repo@sha256:1bcf6764c29cbfdd65b961376b9b1ca229e6a7ed048c5fe37135499c6979ec6d
        name: my-python
        resources: {}
status: {}
