apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-ccgs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-ccgs
    app.kubernetes.io/part-of: test-application
  name: pacman-ccgs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: pacman-ccgs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: pacman-ccgs
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jephilli-tenant/test-application/pacman-ccgs@sha256:4ac046f3388139a63ab2439acaf6c6432b9d92ad7fff8064934170f9475129d4
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
